.TH mommy "1" "%%VERSION_DATE%%" "mommy %%VERSION_NUMBER%%" "user commands"


.SH name
mommy - here to support you~


.SH synopsis
.TP
\fBmommy\fP [\fIoptions\fP] \fIcommand\fP ...
e.g. \fBmommy\fP npm test
.TP
\fBmommy\fP [\fIoptions\fP] \fB-e\fP \fIcommand\fP
e.g. \fBmommy\fP -e "ls -l | wc -l"
.TP
\fBmommy\fP [\fIoptions\fP] \fB-s\fP \fIstatus\fP
e.g. \fBmommy\fP -s $?


.SH description
\fIhttps://github.com/FWDekker/mommy/tree/v%%VERSION_NUMBER%%#readme\fP


.SH options
the following options are just for invoking \fBmommy\fP.
to change mommy's output, you should change the config file.
for more info about config files, check
\fIhttps://github.com/FWDekker/mommy/tree/v%%VERSION_NUMBER%%#configuration\fP.

.TP
\fB-h\fP, \fB--help\fP
opens \fBmommy\fP's manual page~
.TP
\fB-v\fP, \fB--version\fP
displays \fBmommy\fP's version information~
.TP
\fB-e\fP \fIcommand\fP, \fB--eval=\fP\fIcommand\fP
runs \fIcommand\fP and responds to the output.
note that \fIcommand\fP should be given as a single argument~
.TP
\fB-s\fP \fIstatus\fP, \fB--status=\fP\fIstatus\fP
gives output corresponding to exit code \fIstatus\fP~
.TP
\fB-d\fP \fIdirs\fP, \fB--global-config-dirs=\fP\fIdirs\fP
sets global configuration dirs to the colon-separated list in \fIdirs\fP~
.TP
\fB-c\fP \fIfile\fP, \fB--config=\fP\fIfile\fP
tells mommy that she should read your config from \fIfile\fP~
.TP
\fB-1\fP
writes output to \fBstdout\fP instead of \fBstderr\fP~
.TP
\fB--rename=\fP\fIname\fP
changes mommy executable name~
.TP
\fB--remove-rename=\fP\fIname\fP
removes a previous rename and its symlinks~


.SH bugs
\fIhttps://github.com/FWDekker/mommy/issues\fP
