.TH mommy "1" "%%VERSION_DATE%%" "mommy %%VERSION_NUMBER%%" "user commands"


.SH name
mommy - here to support you~


.SH synopsis
.TP
\fBmommy\fP [\fB\-1\fP] [\fB\-c\fP \fIconfig\fP] \fIcommand\fP ...
e.g. \fBmommy\fP npm test
.TP
\fBmommy\fP [\fB\-1\fP] [\fB\-c\fP \fIconfig\fP] \fB-e\fP \fIeval\fP
e.g. \fBmommy\fP -e "ls -l | wc -l"
.TP
\fBmommy\fP [\fB\-1\fP] [\fB\-c\fP \fIconfig\fP] \fB-s\fP \fIstatus\fP
e.g. \fBmommy\fP -s $?


.SH description
https://github.com/FWDekker/mommy/tree/v%%VERSION_NUMBER%%#readme


.SH bugs
https://github.com/FWDekker/mommy/issues
