#!/bin/sh

choose_random_option() {
    count=$(expr $(echo "$1" | grep -o "/" | wc -l) + 1)
    idx=$(shuf -i 1-"$count" -n 1)
    echo "$1" | cut -d "/" -f "$idx"
    return 0
}

# Defaults
MOMMYS_LITTLE="girl"
MOMMYS_PRONOUNS="her"
MOMMYS_ROLES="mommy"

# Load configuration
FILE="$HOME/.config/mommy/config.sh" && test -f $FILE && . $FILE

# Randomize
little=$(choose_random_option "$MOMMYS_LITTLE")
pronoun=$(choose_random_option "$MOMMYS_PRONOUNS")
role=$(choose_random_option "$MOMMYS_ROLES")
message="\n$role knows $pronoun little $little can do better~ ❤️"

# Help the little one :3
if [ $# -eq 0 ]; then
    echo "$message"
elif [ $1 = "-h" ] || [ $1 = "--help" ]; then
    global_man_path="/usr/share/man/man1/mommy.1"
    local_man_path="$(dirname -- "$0")/mommy.1"

    if [ -f $local_man_path ]; then
        man -l "$local_man_path" | cat
    elif [ -f $global_man_path ]; then
        man mommy | cat
    else
        echo "$role could not find the manual for $pronoun little $little~"
    fi
else
    $@ || echo "$message"
fi
